### ISSUE TITLE
ScalaTest FlatSpec tests won't compile

### ISSUE THREAD

**Issue by tampler** [ucb-bar/dsptools#137]
Hello
I'm trying to launch a simple example FlatSpec test from your Documentation page with the following:
sbt "test-only SimpleDsp.SimpleDspModuleSpec"

Output:
[error] Expected ID character
[error] Not a valid command: test-only
...
Getting this error for the trunk version and v1.1.3 checkout. How to fix ?
Thank you for your help!

**Comment by chick** [comment]
try 
`sbt "testOnly SimpleDsp.SimpleDspModuleSpec"`
test-only is a deprecated command
