### ISSUE TITLE
Should we add implicits to dsptools.numbers package object?

### ISSUE THREAD

**Issue by grebe** [ucb-bar/dsptools#22]
I'm finding that 99% of the dsptools code I write requires the following:
```
import dsptools._
import dsptools.numbers._
import dsptools.numbers.implicits._
```

I think there is a use case for using dsptools without the numbers, but I'm not so sure it makes sense to use `dsptools.numbers` without the implicits.

**Comment by chick** [comment]
@grebe is this still a decision that needs to be made

**Comment by shunshou** [comment]
I think it should go into numbers. There's almost no reason to use numbers w/o implicits.

**Comment by shunshou** [comment]
But if we're in agreement -- can I change it in my PR?

**Comment by grebe** [comment]
We should revisit this

**Comment by shunshou** [comment]
As long as typeclass added stuff is separate (doesn't affect expectations from base Chisel), you should just do it, I think.
