### ISSUE TITLE
Document dsptools.Driver usage

### ISSUE THREAD

**Issue by grebe** [ucb-bar/dsptools#32]
Per @shunshou comment in #31.

**Comment by shunshou** [comment]
Code snippet is fine (how to change options from default):

Create case classes related to testerOptions, interpreterOptions, chiselExecutionOptions, firrtlOptions.

```
val options = new TesterOptionsManager {
      testerOptions = TesterOptions(
          isVerbose = false,
          backendName = "verilator",
          // TODO: Figure out what isGenVerilog really does
          isGenVerilog = true)

    }
```

Along with pointers to the fact that 

```
class TesterOptionsManager
  extends ExecutionOptionsManager("chisel-testers")
    with HasTesterOptions
    with HasInterpreterOptions
    with HasChiselExecutionOptions
    with HasFirrtlOptions{
}
``` 

@ [https://github.com/ucb-bar/chisel-testers/blob/master/src/main/scala/chisel3/iotesters/TesterOptions.scala](chisel-testers)

```
case class TesterOptions(
                          isGenVerilog:    Boolean = false,
                          isGenHarness:    Boolean = false,
                          isCompiling:     Boolean = false,
                          isRunTest:       Boolean = false,
                          isVerbose:       Boolean = false,
                          displayBase:     Int     = 10,
                          testerSeed:      Long    = System.currentTimeMillis,
                          testCmd:         mutable.ArrayBuffer[String]= mutable.ArrayBuffer[String](),
                          backendName:     String  = "firrtl",
                          logFileName:     String  = "",
                          waveform:        Option[File] = None) 
```

Are all the possible testerOptions. Same for where to find all the firrtlOptions, chiselOptions, etc. etc. 

I used the code for args -> options to figure out how things are, but even then, the text and the option name aren't all that meaningful all the time. Like what the heck is *isGenVerilog* and how is that different from other stuff??

My biggest concern is with setting up FIRRTL options via stuff @ [https://github.com/ucb-bar/firrtl/blob/65b61b4a614748c699982de5ab8072b21d7f9160/src/main/scala/firrtl/ExecutionOptionsManager.scala](firrtl repo).

The mechanism by which to do something is super confusing. I probably could get more out of reading the Chisel Annotations wiki, but even then, it's hard to figure out. (Also, the Chisel wiki is not super search friendly...)...
