### ISSUE TITLE
Mechanism to convert DspReal [that you know is >=0 b/c of the algorithm] to UInt?

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/dsptools#45]
I kind of need this to go from angles to discrete frequency bin # 's. I'm unsure about the best way to do this. 

At least for FixedPoint, you can theoretically do: FixedPoint -> Rount to SInt -> asUInt conversion...

DspReal you can round too... But is there some way to cast it as an Int and then convert it to an SInt? 

@chick @grebe 

I need something like this fairly urgently.

**Comment by shunshou** [comment]
Ok, so someone can correct me: am I just looking for removeMatissa? (which is a function that's also misspelled...) @grebe @chick ?

**Comment by grebe** [comment]
I think it is called .toUInt, but should probably be changed to asUInt

**Comment by chick** [comment]
Sorry, but I'm not sure, I think @grebe is right.  It looks to me like it is just returning the underlying 64 bit real.  This seems asymmetric between FixedPoint and DspReal, does this currently work?

**Comment by shunshou** [comment]
It's on my to do list of things to check. I actually want just the (signed) integer portion of the real..., possibly rounded.

**Comment by shunshou** [comment]
@chick can you explain your warning?

```
// WARNING! May cause overflow!
11	module BBFToInt(
12	    input  [63:0] in,
13	    output reg [63:0] out
14	);
15	  always @* begin
16	  out <= $rtoi($bitstoreal(in));
17	  end
18	endmodule
```

**Comment by grebe** [comment]
floating point numbers may be larger than maxint

**Comment by shunshou** [comment]
oh ok makes sense lol
