### ISSUE TITLE
Semantics for DspComplex: Imaginary?

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/dsptools#54]
Why not be consistent w/ Breeze, etc. and have c.imag instead of c.imaginary? 

```
class DspComplex[T <: Data:Ring](val real: T, val imaginary: T) extends Bundle {
  override def cloneType: this.type = {
    new DspComplex(real.cloneType, imaginary.cloneType).asInstanceOf[this.type]
  }
```

**Comment by chick** [comment]
I don't have a problem with it, I like it when parallel variables have the same length name.  Could be a quick hacking session project
